apiVersion: v1
kind: Service
metadata:
  name: iam-server
  namespace: application
  labels:
    app: iam-server
    tier: backend
spec:
  selector:
    app: iam-server
  ports:
    - name: http
      protocol: "TCP"
      port: 8080
