kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: application
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
  ports:
    - name: http
      protocol: "TCP"
      port: 80
