networks:
  tactics-trainer:
    name: tactics-trainer

services:
  puzzle-server:
    image: ghcr.io/czarsimon/tactics-trainer/puzzle-server:0.1.0
    ports:
      - 18081:8080
    environment:
      DB_TYPE: sqlite
      DB_FILENAME: /var/lib/puzzle-server/db.sql
      MIGRATIONS_PATH: /etc/puzzle-server/migrations/sqlite
    volumes:
      - ../puzzle-server/resources/db.sql:/var/lib/puzzle-server/db.sql
    networks:
      - tactics-trainer

  iam-server:
    image: ghcr.io/czarsimon/tactics-trainer/iam-server:0.1.0
    ports:
      - 18082:8080
    environment:
      DB_TYPE: sqlite
      DB_FILENAME: /var/lib/iam-server/db.sql
      MIGRATIONS_PATH: /etc/iam-server/migrations/sqlite
      JWT_SECRET: 084415a2891cd35485f690dc19bbcedb22a9432bc962932726f89be77bf56bd7
    volumes:
      - ../iam-server/resources/testing/key-encryption-keys.txt:/etc/iam-server/key-encryption-keys.txt
      - ../iam-server/resources/testing/test.db:/var/lib/iam-server/db.sql
    networks:
      - tactics-trainer

  httplogger:
    image: czarsimon/httplogger:0.8
    ports:
      - 18080:8080
    environment:
      JAEGER_DISABLED: "true"
