networks:
  front-network:
    name: front-network
  application-network:
    name: application-network
  data-network:
    name: data-network

services:
  mysql:
    image: ghcr.io/czarsimon/tactics-trainer/mysql-server:8.0.27-0.1.0
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1615a2817d9a676fc0957a3bf693cd65
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - data-network

  puzzle-server:
    image: ghcr.io/czarsimon/tactics-trainer/puzzle-server:0.7.0
    depends_on:
      - "mysql"
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: puzzleserver
      DB_USERNAME: puzzleserver
      DB_PASSWORD: 0f9a2abc26c46b4794a84b984105410b
      DB_SSL_MODE: "false"
      MIGRATIONS_PATH: /etc/puzzle-server/migrations/mysql
      JWT_SECRET: 084415a2891cd35485f690dc19bbcedb22a9432bc962932726f89be77bf56bd7
    networks:
      - application-network
      - data-network

  iam-server:
    image: ghcr.io/czarsimon/tactics-trainer/iam-server:0.5.0
    depends_on:
      - "mysql"
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: iamserver
      DB_USERNAME: iamserver
      DB_PASSWORD: 7535807ef23504ca84c7200671611ebc
      DB_SSL_MODE: "false"
      MIGRATIONS_PATH: /etc/iam-server/migrations/mysql
      JWT_SECRET: 084415a2891cd35485f690dc19bbcedb22a9432bc962932726f89be77bf56bd7
    volumes:
      - ../iam-server/resources/testing/key-encryption-keys.txt:/etc/iam-server/key-encryption-keys.txt
    networks:
      - application-network
      - data-network

  webapp:
    image: ghcr.io/czarsimon/tactics-trainer/webapp:0.5.0
    networks:
      - front-network

  reverse-proxy:
    image: docker.io/caddy:2.4.6-alpine
    depends_on:
      - "iam-server"
      - "puzzle-server"
      - "httplogger"
      - "webapp"
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - front-network
      - application-network

  httplogger:
    image: czarsimon/httplogger:0.8
    environment:
      JAEGER_DISABLED: "true"
    networks:
      - application-network

volumes:
  mysql-data:
