apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: edge-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  tls:
    - hosts:
        - tacticstrainer.io
      secretName: tacticstrainer-io-certificate
    - hosts:
        - grafana.tacticstrainer.io
      secretName: grafana-tacticstrainer-io-certificate
  rules:
    - host: tacticstrainer.io
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: web-app
              servicePort: 8080
          - path: /api/iam-server/(.*)
            backend:
              serviceName: iam-server
              servicePort: 8080
          - path: /api/puzzle-server/(.*)
            backend:
              serviceName: puzzle-server
              servicePort: 8080
          - path: /api/httplogger/(.*)
            backend:
              serviceName: httplogger
              servicePort: 8080
    - host: grafana.tacticstrainer.io
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: grafana
              servicePort: 80
