apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: edge-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: tacticstrainer.io
      http:
        paths:
          - path: /api/iam-server/(.*)
            backend:
              serviceName: iam-server
              servicePort: 8080
          - path: /api/puzzle-server/(.*)
            backend:
              serviceName: puzzle-server
              servicePort: 8080
          - path: /api/httplogger/(.*)
            backend:
              serviceName: httplogger
              servicePort: 8080
