name: puzzle-server-pipeline

defaults:
  run:
    working-directory: puzzle-server

on:
  push:
    paths:
      - puzzle-server/**
      - .github/workflows/puzzle-server-pipeline.yml

jobs:
  parse-version:
    name: parse-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse.outputs.version }}
      tag-name: ${{ steps.parse.outputs.tag-name }}
      package-name: ${{ steps.parse.outputs.package-name }}
      full-package-name: ${{ steps.parse.outputs.full-package-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: parse
        name: Parse version info
        run: |
          NAME=$(cat package.json | jq .name --raw-output)
          VERSION=$(cat package.json | jq .version --raw-output)
          COMMIT_ID=${GITHUB_SHA:0:7}
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=tag-name::$NAME/$VERSION"
          echo "::set-output name=package-name::$NAME:$VERSION"
          echo "::set-output name=full-package-name::$NAME:$VERSION-$COMMIT_ID"

  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go mod download
      - name: Check code style
        run: go vet ./...
      - name: Run security scan
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.8.1
          $(go env GOPATH)/bin/gosec ./...
      - name: Test
        run: go test ./...

  scan-dependencies:
    name: scan-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"

  build-image:
    name: build-image
    needs:
      - parse-version
      - run-tests
      - scan-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Docker build
        run: |
          echo "Package version: ${{needs.parse-version.outputs.full-package-name}}"
          export IMAGE_NAME="docker.pkg.github.com/czarsimon/tactics-trainer/${{needs.parse-version.outputs.package-name}}"
          docker build -t $IMAGE_NAME .
          docker login https://docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker push $IMAGE_NAME
